// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_introducirnotas.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_mostrarnotas.cpp"
#include "EWIEGA46WW/moc_mostrarpromedio.cpp"
